### ISSUE TITLE
Failure to load - VS Code 1.59

### ISSUE THREAD

**Issue by flipphillips** [cpwood/Pico-Go#97]
## What are the steps to reproduce this issue?
1. Install latest plugin
2. Attempt to use any `pico-go` commands

## What happens?
Errors with command not found.

## What were you expecting to happen?
It to actually work :)

## Any logs, error output, etc?

From Extension Server Logs - 

```
[2021-07-29 16:36:12.037] [exthost] [error] Activating extension ChrisWood.pico-go failed due to an error:
[2021-07-29 16:36:12.037] [exthost] [error] Error: Could not locate the bindings file. Tried:
...
→ /Users/xxx/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/lib/binding/node-v89-darwin-x64/bindings.node
	at bindings (/Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/bindings/bindings.js:126:9)
	at Object.<anonymous> (/Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/lib/darwin.js:2:36)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1315)
...
	at v._activateExtension (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11704)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

## Any other comments?

Definitely a version problem with node serial port driver. 

```
[2021-07-30 12:31:45.350] [exthost] [error] Error: Could not locate the bindings file. Tried:
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/build/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/build/Debug/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/build/Release/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/out/Debug/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/Debug/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/out/Release/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/Release/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/build/default/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/compiled/14.16.0/darwin/x64/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/addon-build/release/install-root/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/addon-build/debug/install-root/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/addon-build/default/install-root/bindings.node
 → /Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/lib/binding/node-v89-darwin-x64/bindings.node
	at bindings (/Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/bindings/bindings.js:126:9)
	at Object.<anonymous> (/Users/fxpppr/.vscode-insiders/extensions/chriswood.pico-go-1.4.2/node_modules/@serialport/bindings/lib/darwin.js:2:36)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:1315)
```

## Regression

Works on same machine/OS with release-version of VSCode. 

## Support info

Can't evaluate because won't load.
```
```

**Comment by flipphillips** [comment]
So, a little digging seems to be a node/typescript version collision. My really naive hypothesis is that insiders is using a newer version of typescript that the node serialport doesn't support?

**Comment by cpwood** [comment]
Pico-Go needed new bindings for modules v89. These will be included in the next release.
